src/bookings/urls.py
from django.urls import path

from bookings import views

app_name = 'bookings'

urlpatterns = [
    path('create/', views.BookingCreateView.as_view(), name='booking-create'),
    path('list/', views.BookingListView.as_view(), name='booking-list'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import generic


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('rooms/', include('rooms.urls')),
    path('bookings/', include('bookings.urls')),
    path('', generic.TemplateView.as_view(template_name='home.html'), name='home'),
]

src/bookings/models.py
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.db import models

from bookings.validators import validate_check_in_date, validate_check_out_date
from rooms.models import TYPE, Room
from utils.models import DateMixin

User = get_user_model()


class Booking(DateMixin):
    uuid = models.UUIDField(
        default=uuid4, max_length=10, primary_key=True, unique=True, verbose_name='Унікальний ідентифікатор'
    )
    user = models.ForeignKey(User, models.PROTECT, verbose_name='Користувач')
    rooms = models.ManyToManyField(Room, verbose_name='Номери')
    persons = models.PositiveSmallIntegerField(default=1, verbose_name='Кількість осіб')
    type = models.PositiveSmallIntegerField(choices=TYPE.choices, default=TYPE.STANDARD, verbose_name='Тип')
    has_children = models.BooleanField(default=False, verbose_name='Чи є діти')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    check_in = models.DateField(verbose_name='Дата заїзду')
    check_out = models.DateField(verbose_name='Дата виїзду')

    def clean(self):
        validate_check_in_date(self.check_in)
        validate_check_out_date(self.check_out, self.check_in)

    class Meta:
        ordering = ['-created']
        verbose_name = 'Бронювання'
        verbose_name_plural = 'Бронювання'

    def __str__(self):
        return str(self.uuid)

    def get_str_rooms(self):
        rooms = [room.number for room in self.rooms.all()]
        return ', '.join(rooms)

    def get_total_price(self):
        prices = [room.room_data.price for room in self.rooms.all()]
        return sum(prices)

    def get_str_type(self):
        return TYPE.choices[self.type][1]

src/bookings/forms.py
from django import forms
from django.core.exceptions import ValidationError

from bookings.models import Booking

NO_PERSONS_ERROR_MESSAGE = 'Persons can only be 1 and more.'


class BookingCreateForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['persons', 'type', 'has_children', 'check_in', 'check_out']
        widgets = {
            'check_in': forms.DateInput(attrs={'type': 'date'}),
            'check_out': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean_persons(self):
        persons = self.cleaned_data.get('persons')

        if persons <= 0:
            raise ValidationError(NO_PERSONS_ERROR_MESSAGE)

        return persons

    def save(self, commit=True):
        self.instance.user = self.user
        return super().save(commit)

src/bookings/views.py
from django.contrib.auth import mixins
from django.urls import reverse_lazy
from django.views import generic

from bookings import forms
from bookings.models import Booking


class BookingCreateView(mixins.LoginRequiredMixin, generic.CreateView):
    model = Booking
    form_class = forms.BookingCreateForm
    template_name = 'bookings/create_form.html'
    success_url = reverse_lazy('bookings:booking-list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class BookingListView(mixins.LoginRequiredMixin, generic.ListView):
    model = Booking
    template_name = 'bookings/list.html'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

src/bookings/templates/bookings/create_form.html
{% extends 'base.html' %}
{% block title %}Booking{% endblock %}
{% block content %}
<div class="form-block">
    <h2 class="form-header">Бронювання</h2>
    <form id="id_booking_form" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-buttons">
            <button id="id_booking_button" type="submit">Забронювати</button>
        </div>

    </form>
</div>
{% endblock %}

src/bookings/templates/bookings/list.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static 'bookings/base.css' %}">
{% endblock %}
{% block title %}Booking List{% endblock %}
{% block content %}
<div id="id_booking_list">
    <a id="id_booking_room_link" href="{% url 'bookings:booking-create' %}">Забронювати кімнату</a>
    <h2 class="header">Список Бронювань</h2>
    {% for booking in object_list %}
        <div class="card">
            <p>UUID: {{ booking.uuid }}</p>
            {% if booking.rooms.all %}
                <p>Кімнати: {{ booking.get_str_rooms }}</p>
            {% else %}
                <p>Кімнати: Manager doesn't choose room/rooms for you.</p>
            {% endif %}
            <p>Осіб: {{ booking.persons }}</p>
            <p>Тип: {{ booking.get_str_type }}</p>
            {% if booking.rooms.all %}
                <p>Тотальна сума: {{ booking.get_total_price }} UAH</p>
            {% else %}
                <p>Тотальна сума: -</p>
            {% endif %}
            {% if booking.has_children %}
                <p>Є діти: <input type="checkbox" checked disabled></p>
            {% else %}
                <p>Є діти: <input type="checkbox" disabled></p>
            {% endif %}
            <p>Дата заїзду: {{ booking.check_in|date:"d N Y" }}</p>
            <p>Дата виїзду: {{ booking.check_out|date:"d N Y" }}</p>
            <p>Дата створення: {{ booking.created|date:"d N Y, h:i A" }}</p>
        </div>
    {% empty %}
        <p id="id_empty_list_message">Поки що ви нічого не бронювали.</p>
</div>
{% endfor %}
{% endblock %}