src/accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('sing-up/', views.UserRegisterView.as_view(), name='user-register'),
    path('sing-up/success/', views.UserRegisterSuccessView.as_view(), name='user-register-success'),
    path('sing-up/continue/', views.UserRegisterContinueView.as_view(), name='user-register-continue'),
    path('confirm-email/<uidb64>/<token>/', views.UserConfirmEmailView.as_view(), name='user-confirm-email'),
    path('confirm-email/success/', views.UserConfirmEmailSuccessView.as_view(), name='user-confirm-email-success'),
    path('confirm-email/failure/', views.UserConfirmEmailFailureView.as_view(), name='user-confirm-email-failure'),
    path('sing-in/', views.UserLoginView.as_view(), name='user-login'),
    path('sing-out/', views.UserLogoutView.as_view(), name='user-logout'),
    path('', views.UserAccountView.as_view(), name='user-account'),
]

src/bookings/urls.py
from django.urls import path

from bookings import views

app_name = 'bookings'

urlpatterns = [
    path('create/', views.BookingCreateView.as_view(), name='booking-create'),
    path('list/', views.BookingListView.as_view(), name='booking-list'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import generic


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('rooms/', include('rooms.urls')),
    path('bookings/', include('bookings.urls')),
    path('', generic.TemplateView.as_view(template_name='home.html'), name='home'),
]

src/rooms/urls.py
from django.urls import path

from rooms import views

app_name = 'rooms'
urlpatterns: list = [
    path('list/', views.RoomDataListView.as_view(), name='room-list'),
]

src/utils/models.py
from django.db import models


class DateMixin(models.Model):
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

src/utils/templates/includes/footer.html
<footer>
    <div>
        <a id="id_home_link" href="{% url 'home' %}">Головна</a>
        <a id="id_room_list_link" href="{% url 'rooms:room-list' %}">Кімнати</a>
        <a id="id_about_us_link" href="#">Про Нас</a>
        <a id="id_service_link" href="#">Послуги</a>
        <a id="id_help_service_link">Служба підтримки</a>
    </div>
</footer>

src/utils/templates/includes/navbar.html
<nav id="id_navbar">
    <div>
        <a id="id_home_link" href="{% url 'home' %}">Головна</a>
        <a id="id_room_list_link" href="{% url 'rooms:room-list' %}">Кімнати</a>
        <a id="id_about_us_link" href="#">Про Нас</a>
        <a id="id_service_link" href="#">Послуги</a>
    </div>
    <div></div>
    <div>
        {% if user.is_authenticated %}
            <a id="id_booking_link" href="{% url 'bookings:booking-list' %}">Бронювання</a>
            <a id="id_account_link" href="{% url 'accounts:user-account' %}">Аккаунт</a>
            <a id="id_logout_link" href="{% url 'accounts:user-logout' %}">Вийти</a>
        {% else %}
            <a id="id_registering_link" class="item" href="{% url 'accounts:user-register' %}">Зареєструватися</a>
            <a id="id_login_link" href="{% url 'accounts:user-login' %}">Війти</a>
        {% endif %}
    </div>
</nav>